ALTER TABLE usuarios ADD COLUMN fonte TEXT NOT NULL DEFAULT 'arial';
ALTER TABLE usuarios ADD COLUMN tamanho_fonte TEXT NOT NULL DEFAULT 'm';
ALTER TABLE usuarios ADD COLUMN tema TEXT NOT NULL DEFAULT 'claro';
